server:
  port: 8080


# API Gateway Config
spring:
  application:
    name: gateway



  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
          filters:
            - StripPrefix=2

        - id: book-service
          uri: lb://BOOK-SERVICE   # Use the direct service URL
          predicates:
            - Path=/api/v1/bookservice/**
          filters:
            - StripPrefix=2



        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/